spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: library
    password: strong_pass
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: 'classpath:db/migration'
    create-schemas: true
    schemas: [ 'library' ]
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    allow-circular-references: true
