app:
  dao:
    question-dao-csv:
      path: "classpath:questionnaire.csv"
      delimiter: ";"
      question-position: 0
      right-answer-position: 1
  services:
    test-service-impl:
      part-right-answers: 70
      start: "Welcome to the test!"
      finish: "\n%s %s, we hope you don't worry about it:)"
      win: "You are extra smart, you answered %d / %d"
      fail: "You are extra stupid, you answered %d / %d"
    question-service-impl:
      input-answer: "Input the answer: "
      input-number-answer: "Input the number of the answer: "
    user-service-impl:
      input-name: "Input your name: "
      input-surname: "Input your surname: "