spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: library
    password: strong_pass
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql