app:
  dao:
    question-dao-csv:
      delimiter: ";"
      question-position: 0
      right-answer-position: 1
    locale-provider:
      languages:
        -
          language: ${app.dao.locale-provider.language-description.languages}
          shortDescription: ${app.dao.locale-provider.language-description.shortDescription}
          description: ${app.dao.locale-provider.language-description.description}
          path: ${app.dao.locale-provider.language-description.path}
        -
          language: "en-EN"
          shortDescription: "En"
          description: "English"
          path: "classpath:questionnaire_en.csv"
      language-description:
        language: "ru-RU"
        shortDescription: "Ру"
        description: "Русский"
        path: "classpath:questionnaire_ru.csv"
  services:
    test-service-impl:
      part-right-answers: 70